### ISSUE TITLE
Can not link pugixml in VS2017 release build 

### ISSUE THREAD

**Issue by hiroMTB** [openframeworks/apothecary#115]
I can not link pugixml in Visual Studio 2017 release mode.
This only happens in the very limited case when I use ofxSvg(but oF's svg example doesn't have this problem)

The error is,

`pugixml.lib' was created with an older compiler than other objects; rebuild old objects and libraries`

Following formula could be the reason since it apparently uses vs 2015.
https://github.com/openframeworks/apothecary/blob/ce1d8074d0f158e22dab9f4216f61acc0ddac7ef/apothecary/formulas/pugixml.sh#L47-L63

This issue on pugixml repo might also be related.
https://github.com/zeux/pugixml/issues/157

I just compile pugixml 1.9 by myself and replaced oF's bugixml 1.8.
It works ok so far.

We might need to provide different binaries for vs2015 and vs2017 (more...?)

**Comment by oxillo** [comment]
@hiroMTB 
I think this issue has been corrected. Can you confirm and close the issue ?
Thanks

**Comment by hiroMTB** [comment]
Hello, thank you for follow-ups. Sorry I don't remember which svg file made
this issue. I should have uploaded exact file. In the meantime, shall we
close? And re-open when we find it again.

**Comment by arturoc** [comment]
i also think this was fixed a while ago. thanks!
