### ISSUE TITLE
Problem building addon lib

### ISSUE THREAD

**Issue by michaelbaisch** [openframeworks/apothecary#116]
Hello,

I'm having trouble building libs from addons. The problem seems to be that the `LIBS_DIR` path is wrong in the copy phase. Digging into the code the problem seems to be that `IS_CUSTOM_LIBS_DIR` is set to `1` here (Line 1214):

```bash
if [ "$LIBS_DIR" == "" ] ; then
  LIBS_DIR=$APOTHECARY_DIR/$REL_LIBS_DIR
else # manually set
  case $LIBS_DIR in
    /*) : ;; # absolute path
    *) LIBS_DIR=$WD/$LIBS_DIR ;; # relative path
  esac
  IS_CUSTOM_LIBS_DIR=1
fi
```

Because `LIBS_DIR` is already set here (Line 124):

```bash
LIBS_DIR=$(realpath ${APOTHECARY_DIR}/../)
```

And this way the `LIBS_DIR` isn't set correctly in `doCommand()` (Line 628):

```bash
# set libs dest dir to addon/libs if it hasn't been manually set
if [ $IS_CUSTOM_LIBS_DIR == 0 ] ; then
  LIBS_DIR=$ADDONS_DIR/$1/libs
fi
```

If I comment `IS_CUSTOM_LIBS_DIR=1` in the first code block everything works as expected. Did I understand something wrong or is this a bug?

Thanks,
Michael

**Comment by danoli3** [comment]
Okay I tested building with addon directly and it seemed to work. I noticed one failure with LIBS_ROOT if referencing other libraries as dependency so I've added another variable that won't break to be used for these addons if referencing other built /out locations.

**Comment by danoli3** [comment]
Copy Phase is working correctly though now can confirm
