### ISSUE TITLE
ci.openFrameworks Security

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#119]
Can we beef up the security a little bit of the system:

Security Upgrades:
- [ ] https for ci.openframeworks.com (can use https://letsencrypt.org for free)
- [ ] MD5 checksum generated for binaries and output in directory or subdirectory (to minimise clutter).

Potential Server Load / Protection: 
- [ ] Server Cloud Array via Free Option https://www.cloudflare.com (just for distributed load of binary download around the world).

**Comment by oxillo** [comment]
MD5 check sum implemented in #123
