### ISSUE TITLE
macos mojave 10.14.2 build and folder name errors

### ISSUE THREAD

**Issue by kyeshmz** [openframeworks/apothecary#138]
Hi, i am working on some of the folder attributes for the build script under this issue here.
https://github.com/openframeworks/openFrameworks/issues/6372

It seems that I can't use apo even in a regular build under mojave.
Using sample code like `./apothecary -t osx  -a 64 update assimp ` , it fails with error like below.

It seems apparent that its trying to build on i386, which isn't relevant for macos, but do I need to update each formula to allow -a 64 not to build i386? 

Thanks

```
+ local 'buildOpts=--build build/osx
            -DBUILD_SHARED_LIBS=OFF
            -DASSIMP_BUILD_STATIC_LIB=1
            -DASSIMP_BUILD_TESTS=0
            -DASSIMP_BUILD_SAMPLES=0
            -DASSIMP_ENABLE_BOOST_WORKAROUND=1
            -DASSIMP_BUILD_STL_IMPORTER=0
            -DASSIMP_BUILD_BLEND_IMPORTER=0
            -DASSIMP_BUILD_3MF_IMPORTER=0'
+ cmake -G 'Unix Makefiles' --build build/osx -DBUILD_SHARED_LIBS=OFF -DASSIMP_BUILD_STATIC_LIB=1 -DASSIMP_BUILD_TESTS=0 -DASSIMP_BUILD_SAMPLES=0 -DASSIMP_ENABLE_BOOST_WORKAROUND=1 -DASSIMP_BUILD_STL_IMPORTER=0 -DASSIMP_BUILD_BLEND_IMPORTER=0 -DASSIMP_BUILD_3MF_IMPORTER=0 '-DCMAKE_C_FLAGS=-arch i386 -arch x86_64 -O3 -DNDEBUG -funroll-loops -mmacosx-version-min=10.9' '-DCMAKE_CXX_FLAGS=-arch i386 -arch x86_64 -stdlib=libc++ -O3 -DNDEBUG -funroll-loops -std=c++11 -mmacosx-version-min=10.9' .
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- broken
CMake Error at /usr/local/Cellar/cmake/3.15.3/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/kkshmzmbp/Documents/openFrameworks/scripts/apothecary/apothecary/build/assimp/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_c010d/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_c010d.dir/build.make CMakeFiles/cmTC_c010d.dir/build
    Building C object CMakeFiles/cmTC_c010d.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch i386 -arch x86_64 -O3 -DNDEBUG -funroll-loops -mmacosx-version-min=10.9  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_c010d.dir/testCCompiler.c.o   -c /Users/kkshmzmbp/Documents/openFrameworks/scripts/apothecary/apothecary/build/assimp/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_c010d
    /usr/local/Cellar/cmake/3.15.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c010d.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch i386 -arch x86_64 -O3 -DNDEBUG -funroll-loops -mmacosx-version-min=10.9  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/usr/local/opt/ruby/lib  CMakeFiles/cmTC_c010d.dir/testCCompiler.c.o  -o cmTC_c010d 
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: dynamic main executables must link with libSystem.dylib for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_c010d] Error 1
    make: *** [cmTC_c010d/fast] Error 2
```

**Comment by arturoc** [comment]
we haven't updated the scripts yet to only build 64bits and since the ci servers still run on a maxos / xcode version that supports i386 we haven't had any problem with it. In any case yes you would need to update every formula to work on newer versions of xcode that don't support i386 anymore

not sure what's the best solution though, if completely removing i386 already or leaving it optionally unless the architecture is explicitly set to -a64

**Comment by kkshmz** [comment]
I think it really depends on who of the maintainers still need the i386 option, if it is not needed, we can go ahead with making x86_64 only the default.

So recapping on the course of action,
- update scripts to allow architecture -a 64 and remove excess i386
- create new ci files for newer xcode ( 10~?)

**Comment by arturoc** [comment]
No, the ci should stay the same so the compiled libraries are compatible with older versions. 

If possible I would add an option so if -a64 is explicitly passed then it only compiles for x86_64 but otherwise it compiles both architectures or that it detects the version of xcode and compiles only for x68_64 if i386 is not supported anymore. If it's much more work than simply removing i386 i can imagine simply removing i386 should be fine but i would then only merge the change after the next release to at least keep compatibility for one more release

**Comment by ofTheo** [comment]
I agree I think its okay for now, but we'll need to address it soon as 10.15 will drop 32bit support. 
We can probably make something that detects the macOS version and then only builds 64bit for 10.15 and above. ( or 10.14 and above )

**Comment by kkshmz** [comment]
Should the detection be done at the apothecary script level?
Like 
`sw_vers -productVersion | awk  '{if($1>10.13)print$1}'`
Then something like `10.14.3`  would come back if it is over 10.13.

Then pass that as an conditional to put -a 64 for the scripts?

**Comment by arturoc** [comment]
i think deciding based on the version should be safe. apothecary will mostly be run on the CI servers and the fact the libraries contain a 32bit version is not a problem for systems that only support 64bits.

This change mostly allows people to run apothecary in their own computers for testing. I don't think we'll need this in the CI servers until much later, when anything bellow 10.15 is not supported by travis.

@kkshmz if you want to try to add version detection that would be great.

**Comment by ofTheo** [comment]
this should be fixed now in the master branch. 
we are now only building 64bit and arm64. building apothecary manually does require Xcode 12.2 though now.
