### ISSUE TITLE
Not sure if we still need OpenSSL patch for VS

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#145]
We have this patch applied:
https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/openssl/winOpenSSL.patch 

At this step:
https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/openssl/openssl.sh#L48

Looking at the files in:
https://www.openssl.org/source/openssl-1.1.0h.tar.gz 

There isn't a file called: 'util/mk1mf.pl' 

So the formula hangs for a while with: 
```
The text leading up to this was:
--------------------------
|--- /util/mk1mf.pl     Mon May 25 22:21:41 2015
|+++ /util/mk1mf.pl     Mon May 25 22:13:09 2015
--------------------------
File to patch:
```

Removing the patch from prepare allows for a successful build for openssl for VS

I can do a PR removing the lines from the formula. 
https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/openssl/openssl.sh#L48

**Comment by arturoc** [comment]
patches are only used to get some formulas to build on platforms where they don't. i guess a change in the compiler has made this patch obsolete. if it builds without it go for it
