### ISSUE TITLE
Big Sur and backwards compatibility with curl

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#176]
So everything so far in apothecary seems to work on older macOS versions when built with Xcode 12 except curl. 
Building a arm64 / X86_64 lib on 10.15 with Xcode > 11.3 ( Xcode 12 is needed for arm64 ) results in a linking error 
`Undefined symbols for architecture x86_64: "___darwin_check_fd_set_overflow"` when running on 10.14 / Xcode 11. 

This seems to be a common issue affecting a lot of libaries, though the only solution suggested across many pages is to upgrade to Xcode > 11.3.1. Which means 10.15 / Catalina. ( see: https://github.com/react-native-community/upgrade-support/issues/119 and:  https://github.com/curl/curl/issues/5210 etc  - note: its not a bug just a backwards compatible breaking change in FD_SET ) 

The only solution I have found so far is to lipo the curl.a and replace the  X86_64  slice with one created on a 10.14 machine. 
When I do this the lib works both on 10.14 / Intel  as well as 11.0 / Apple Silicon. 

The Github Actions 10.15 OS does have Xcode 11.3.1 installed which should allow for a non breaking build. 
See: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md 

So in a pinch we could build the arm64 version with Xcode 12 and then build the X86_64 version with Xcode 11.3.1 which **_should_** work. 

The other option would be to only support 10.15 as a min OS going forward ( which seems a shame seeing as its just one lib ). 

Anyway would be great to get some thoughts on this. 
Its probably the only thing left lib wise to still figure out. 

Happy New Year all! :)

**Comment by Daandelange** [comment]
Hello, You posted this already 2 years ago.
Just to report my finding, I have been able to run oF-0.11.2 release (zip) on osx 10.12 (intel 64) by **1.** [recompiling rtAudio manually](https://github.com/openframeworks/apothecary/pull/202) and **2.** by grabbing libcurl.a from OF 0.11.0 as suggested by eduard in the mention right above. I tried recompiling libcurl using apothecary but it fails on building libcurl, even after removing `arm` stuff from the formula.
