### ISSUE TITLE
Issue with linux gcc4 build of Poco breaking nightly builds

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#185]
When building the PG on the OF CI server I get: 

`openFrameworks_pkg_creation/addons/ofxPoco/libs/poco/lib/linux64/libPocoXML.a(AbstractContainerNode.o):AbstractContainerNode.cpp:function Poco::XML::AbstractContainerNode::findNode(__gnu_cxx::__normal_iterator<char const*, std::string>&, __gnu_cxx::__normal_iterator<char const*, std::string> const&, Poco::XML::Node const*, Poco::XML::NamespaceSupport const*): **error: undefined reference to 'Poco::NumberParser::parse(std::string const&, char)**'`

Before there were more linking issues which were resolved as Github Actions Linux build was defaulting to GCC 5 even after GCC 4.9 was installed. ( [This commit](https://github.com/openframeworks/apothecary/commit/99d57381d1db93489044eb8bf3483371e4f6c056) fixed that issue ) 

The question I have now is should gcc4 Linux64 builds be using `-std=c++11` or `-std=c99` which is what it is defaulting to right now.  

( I'll try a build with -std=c++11 and see what happens, but any thoughts would be awesome )

**Comment by arturoc** [comment]
we could also remove gcc4 builds already if they are problematic. we mostly kept them cause travis was still using gcc4 in the vms we used but if github actions uses a newer version, which i guess it does, and since gcc 6 or more has been the default for some years now all major distributions, we can remove gcc4 and even 5 without problem.

**Comment by ofTheo** [comment]
Ahh okay - thanks @arturoc! 
That makes total sense ( and is also a big relief! :) 

I'll see if just doing gcc6 lets everything build without issue. Much appreciated!
