### ISSUE TITLE
assimp.a is 300MB for macOS - new releases fix size issue but have broken skeleton matrix / animations. wait for fix upstream. 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#198]
not sure what happened between 0.11.0 and 0.11.1 but assimp went from 27MB to over 300MB.

**Comment by danoli3** [comment]
Bitcode?

**Comment by dimitre** [comment]
I've tested today and assimp 5.0.1 is 400Mb, newer ones like 5.1.0 are 40Mb but they are having issues with model and animation. I've tested and reported back in this already opened issue
https://github.com/assimp/assimp/issues/4487

**Comment by ofTheo** [comment]
Yeah, I tried 5.1.6 from @danoli3's Android PR branch and it was around 40MB too. 
I might update the issue title and leave open.  Hopefully it will get fixed soon and we can pull in.

**Comment by ofTheo** [comment]
Just as an update I tried a bunch of different flags and options for building assimp 5.0.1 and it is always over 300MB. 
I tried several things in here - https://github.com/assimp/assimp/issues/424 

So I guess its better just to see if they fix the matrix / skeleton stuff soon and then use their latest build.

**Comment by danoli3** [comment]
Cool! I will work on it today
