### ISSUE TITLE
BinTray is sunset - need new links for boost 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#203]
breaking the CI currently. 
![image](https://user-images.githubusercontent.com/144000/117223082-c5937200-adc1-11eb-9bde-1e98d0eda6f9.png)

see the sunset notice here: https://bintray.com

**Comment by arturoc** [comment]
this seems to be the current url:

https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

**Comment by ofTheo** [comment]
Thanks @arturoc! 
Will merge if this PR passes.

**Comment by danoli3** [comment]
On this note, can we update to latest 1.74.0 boost as well, android having
so many problems without it compiling

Heaps of patches in here: https://github.com/moritz-wundke/Boost-for-Android

**Comment by arturoc** [comment]
That shouldn't be a problem. Indeed we only use boost to provide std::filesystem which should now be supported by most compilers so we could even remove it in soem platforms like android where we can control the toolchain version and default to std everywhere
