### ISSUE TITLE
iOS Simulator Need to compile arm64 with simulator libs 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#208]
This involves also changing to use apple's new requirement of .frameworks to encapsulate and name the libraries ! 

Which in turn involves changing core templates in iOS / tvOS !

**Comment by danoli3** [comment]
Also BITCODE is required now

**Comment by ofTheo** [comment]
I think this is a big priority now as we're starting to see issues on the forum with people getting errors when using the simulator. 

Probably another option which might be a bit less work would be to separate out the libs for iOS Device and Simulator by folder and then link to them based on target. 

eg: 
`libs/ios/device/opencv.a`
`libs/ios/simulator/opencv.a` 

Upside is it would be backwards compatible. 
Downside is it might not work for catalyst apps?

**Comment by danoli3** [comment]
Apple no longer requires BITCODE :D 

Okay massive progress here! 
Due to the CMake overhaul of dependancies and finalising Patching dependancies on the Android / Massive Apothecary changes PR ! Branching off that I have successfully got many dependancies building with support for the targets:

- iOS arm64 
- iOS arm64 (simulator)
- iOS x86_64 (simulator) 
- iOS x86_64 (Mac Catalyst) 
- iOS arm64 (Mac Catalyst)
- macOS arm64 
- macOS x86_64
- tvOS arm64
- tvOS x86_64 (simulator) 
- tvOS arm64 (simulator) 
- 

<img width="441" alt="Screenshot 2023-07-29 at 12 56 32 pm" src="https://github.com/openframeworks/apothecary/assets/830748/31885ecd-0035-43fd-ae2e-530fe7b43344">

Furthermore, I have code that will be able to merge these into the new framework system to allow different lib types in the same fat lib. These can even include multiple platforms in one, or separated we can decide later

**Comment by ofTheo** [comment]
Yay!! 👏👏👏
That’s awesome news!

**Comment by kritzikratzi** [comment]
@danoli3 are you still working on this? 

my changes seem to work (i still have issues with sound streams in the simulator, but that seems unrelated). 

i'm happy to clean up my changes and make a PR, but i don't really to want to waste my time (or yours) if there's already a better solution

**Comment by danoli3** [comment]
Completed
