### ISSUE TITLE
Current PRs / Actions failing for msys2 and SVGTiny 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#247]
Seems like svgtiny is failing now even though there haven't been any changes to the formula. 
What is weird is it has been working and passes in the master branch but any current CI runs errors ( for all msys2 / ucrt64 etc platforms ). @oxillo any chance you could take a look?

from: https://github.com/openframeworks/apothecary/actions/runs/3433644522/jobs/5724183530 
```
cc -c src/svgtiny_gradient.c -o src/svgtiny_gradient.o -O2 
src/colors.gperf:17:10: fatal error: svgtiny.h: No such file or directory
   17 | #include "svgtiny.h"
      |          ^~~~~~~~~~~
compilation terminated.
cc -c src/svgtiny_list.c -o src/svgtiny_list.o -O2 
src/svgtiny.c:17:10: fatal error: dom/dom.h: No such file or directory
   17 | #include <dom/dom.h>
      |          ^~~~~~~~~~~
compilation terminated.
src/svgtiny_gradient.c:14:10: fatal error: svgtiny.h: No such file or directory
   14 | #include "svgtiny.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:72: src/autogenerated_colors.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:72: src/svgtiny.o] Error 1
make: *** [Makefile:72: src/svgtiny_gradient.o] Error 1
src/svgtiny_list.c:15:10: fatal error: svgtiny.h: No such file or directory
   15 | #include "svgtiny.h"
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by ofTheo** [comment]
@themancalledjakob has a potential fix here: 
https://github.com/openframeworks/apothecary/pull/243#issuecomment-1312146615 

I wonder if we can just include both in the export that way it gets picked up for both possibilities?
Still super strange that it just stopped working without any changes to the formula 🙂

**Comment by themancalledjakob** [comment]
:) true, it's a bit weird that it worked before, but hope that's it though! i had the same error and this fixed it
```diff
diff --git a/apothecary/formulas/svgtiny/svgtiny.sh b/apothecary/formulas/svgtiny/svgtiny.sh
index c3cb35f..2fe49da 100644
--- a/apothecary/formulas/svgtiny/svgtiny.sh
+++ b/apothecary/formulas/svgtiny/svgtiny.sh
@@ -71,12 +71,8 @@ function build() {
             export LDFLAGS=-L$SYSROOT/usr/lib
             export CFLAGS=-I$SYSROOT/usr/include
         fi
-        
-        export CFLAGS="$(pkg-config libxml-2.0 --cflags)"
-        
-        if [ "$TYPE" == "linuxarmv6l" ] || [ "$TYPE" == "linuxarmv7l" ] ; then
-            export CFLAGS="-I$LIBS_DIR/libxml2/include"
-        fi
+
+        export CFLAGS="-I$LIBS_DIR/libxml2/include"
         
         make clean
            make -j${PARALLEL_MAKE}

```

**Comment by themancalledjakob** [comment]
I see that here [apothecary/formulas/svgtiny/svgtiny.sh](https://github.com/openframeworks/apothecary/pull/245/commits/bc6cf27cd6ae3c2c822d54e5d44ebfeb978496e5#diff-f07dcc7915792535f8e8a37f9cf69ba8a52938040961724c3315a591bbefe503) is still a call to pkg-config ```export CFLAGS="$(pkg-config libxml-2.0 --cflags) -I$LIBS_DIR/libxml2/include"```

**Comment by ofTheo** [comment]
yeah I thought maybe if one of the platforms was using pkg-config it would support both possibilities. 
I'll do a separate PR for this so its not tied up with the H264 / videoInput stuff I am adding :)

**Comment by themancalledjakob** [comment]
aaah, i see :)
try this:
```
export CFLAGS="$(pkg-config libxml-2.0 --cflags)" || export CFLAGS="-I$LIBS_DIR/libxml2/include"
```

**Comment by danoli3** [comment]
Yeah had this problem heaps on android patch branch
 it’s the dependency

**Comment by themancalledjakob** [comment]
@ofTheo
sorry for not noticing, previous version had a logical error.
This is what you need:
```
export CFLAGS="$(pkg-config libxml-2.0 --cflags || echo \"-I$LIBS_DIR/libxml2/include\")"
```

**Comment by ofTheo** [comment]
Thanks! 
I just tried it here and still get an error though it it is different now. 

https://github.com/openframeworks/apothecary/actions/runs/3452128137/jobs/5761823592 

```
cc -c libwapcaplet/src/libwapcaplet.c -o libwapcaplet/src/libwapcaplet.o -O2 "-I/d/a/apothecary/apothecary/scripts/../out/libxml2/include"  -D_BSD_SOURCE -D_DEFAULT_SOURCE -DWITHOUT_ICONV_FILTER -fPIC -I/d/a/apothecary/apothecary/apothecary/build/svgtiny/include/ -I/d/a/apothecary/apothecary/apothecary/build/svgtiny/src -Wall -W -Wundef -Wpointer-arith -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -std=c99 -Ilibdom/include -Ilibdom/src -Ilibdom/bindings -Ilibwapcaplet/include -Ilibparserutils/include -Ilibparserutils/src -Ilibxml2/include
[683](https://github.com/openframeworks/apothecary/actions/runs/3452128137/jobs/5761823592#step:4:684)
libdom/bindings/xml/libxml_xmlparser.c:12:10: fatal error: libxml/parser.h: No such file or directory
```

**Comment by oxillo** [comment]
I've looked at the log and the libxml2 package is not found.

Looking in details at the setup of the GitHub actions, the libxml2 is not installed in the UCRT64 system.
I'll submit a PR to fix that.

**Comment by ofTheo** [comment]
also thanks @themancalledjakob for all your help / suggestions!!
