### ISSUE TITLE
CI build libs for linuxaarch64 to work with RPI 4

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#269]
openFrameworksLibs_master_linuxaarch64.tar.bz2
to work together with this future PR - https://github.com/openframeworks/apothecary/pull/233

**Comment by ofTheo** [comment]
Haha! yeah - this will be a fun one 😆

**Comment by ofTheo** [comment]
Going to take a stab at getting this setup for Debian 11 
https://github.com/abhiTronix/raspberry-pi-cross-compilers/wiki/64-Bit-Cross-Compiler:-Installation-Instructions
