### ISSUE TITLE
libusb not present on ofxKinect, vs2019

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#271]
cc @ofTheo @danoli3 
I've just noticed libusb is not being bundled in the install script in ofxKinect for windows
"install from github"

It seems openCv libs are not being installed also.

**Comment by dimitre** [comment]
I've finally discovered the issue I thought was related to projectGenerator. if we install from git, in windows and install libs via script, openCV is incomplete.
I think nightly is using this script to bundle the releases, so the projects are broken even if it packs the libraries correctly later.

**Comment by danoli3** [comment]
Yeah let me package up zip of latest to test

**Comment by danoli3** [comment]
Is this still occurring? @dimitre

**Comment by danoli3** [comment]
Fixed
