### ISSUE TITLE
ofxSvg incomplete on aarch64

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#273]
libxml2 and svgtiny are not being bundled on the nightly for aarch64.
Is that something easy to update on apothecary?

related: 
https://forum.openframeworks.cc/t/of-on-khadas-vim4/42316/12

**Comment by ofTheo** [comment]
@dimitre I think its just missing the `linuxaarch64` target everywhere there is `linuxarmv6l` 
eg: https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/svgtiny/svgtiny.sh#L68 

Might be the same for libxml2 too. 

I think the fix would be to just add `linuxaarch64` checks everywhere there is `linuxarmv6l`

**Comment by dimitre** [comment]
Nice! I've submitted a PR here to update this platforms
https://github.com/openframeworks/apothecary/pull/276

**Comment by dimitre** [comment]
Wowww that's great news @ofTheo
