### ISSUE TITLE
[feature request] - have fmt added to the libs

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#304]
https://github.com/fmtlib/fmt
it would be great to have fmt added to the libs, so we can fix the last warnings about sprintf in the core
and prepare to use std::format in c++20 when it is time

related: 
- https://github.com/openframeworks/openFrameworks/issues/6929

**Comment by danoli3** [comment]
Oh yes this is a a good idea, these warning logs are getting hectic from this
