### ISSUE TITLE
Libraries for windows installing in a different folder - Windows only

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#315]
I've noticed on both ofxKinect and ofxOpenCv some additional folders are being created, like
addons / ofxOpenCv / libs / ippicv / ippicv (we have to move one folder up)
addons / ofxOpenCv / libs / opencv / opencv (we have to move one folder up)

same for libusb and maybe some others

cc @ofTheo @danoli3

**Comment by danoli3** [comment]
Looking into this now as yeah nightly goes to download script. 

Might be worth thinking about adding releases targetted to numbers, and in oF core having a way like -b to specify which version:

download_libs.sh -v 12.0.0 

or something. 

Okay I have a fix for the above already

**Comment by danoli3** [comment]
Okay that one should solve it ^

**Comment by dimitre** [comment]
Greatt news!

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7819#event-11226060176
