### ISSUE TITLE
Rename osx to macos 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#320]
I was speaking to someone recently and mentioned OSX, their context is a developer and they said, what's that...

So terminology OSX while, historically correct, maybe confusing new developers who may be looking to use a framework system like openFrameworks. With all these massive changes currently doing for macOS ideal moment in code is now.

I think its time we updated our references in code and distribution to reflect the Apple Naming convention. 

### Proposed change: osx -> macos 

Ideal time to do it can start with Apothecary and go from there. 

Thoughts?

**Comment by dimitre** [comment]
Let's do it. I can make changes in projectGenerator commandline accordingly 
I don't know anything Electron, so somebody else can jump too

**Comment by ofTheo** [comment]
Oh god, can we wait on that until at get bleeding working with OF/OF. 

That’s a big change.

**Comment by danoli3** [comment]
Yeah can definitely wait till after the bandages applied

**Comment by danoli3** [comment]
Since new script merging for multi apple platforms now, this became a bit easier since we can just target both

**Comment by dimitre** [comment]
I've submitted two PRs meant to be merged at once
https://github.com/openframeworks/openFrameworks/pull/7896
https://github.com/openframeworks/projectGenerator/pull/483

**Comment by danoli3** [comment]
Awesome nice one!!

Let’s rebase this ontop after macOS and project stuff merged in once we
confirm macOS libs all good.

I think I’m going to have to fix OpenSSL and curl after all damn. Ah well

**Comment by danoli3** [comment]
yeah so I think we repurpose the macOS to be the Mega platform, so lets leave osx as is
