### ISSUE TITLE
Can't Run on Windows

### ISSUE THREAD

**Issue by danzeeeman** [openframeworks/apothecary#345]
danm@DESKTOP-ERAJ33U /cygdrive/e/of_v0.12.0_vs_release/of_v0.12.0_vs_release/apothecary
$ ./apothecary/apothecary --help
./apothecary/apothecary: line 25: $'\r': command not found
./apothecary/apothecary: line 28: $'\r': command not found
./apothecary/apothecary: line 30: $'\r': command not found
./apothecary/apothecary: line 34: $'\r': command not found
./apothecary/apothecary: line 37: $'\r': command not found
./apothecary/apothecary: line 41: $'\r': command not found
./apothecary/apothecary: line 44: $'\r': command not found
./apothecary/apothecary: line 46: $'\r': command not found
./apothecary/apothecary: line 51: $'\r': command not found
./apothecary/apothecary: line 54: $'\r': command not found
./apothecary/apothecary: line 57: $'\r': command not found
./apothecary/apothecary: line 60: $'\r': command not found
./apothecary/apothecary: line 63: $'\r': command not found
./apothecary/apothecary: line 67: $'\r': command not found
./apothecary/apothecary: line 72: syntax error near unexpected token `fi'
'/apothecary/apothecary: line 72: `fi;

**Comment by danoli3** [comment]
Please use bleeding branch.

Windows works I’ve been building all day on windows

**Comment by danoli3** [comment]
Maybe best to download apothecary bleeding zip from here and drop it in
your release folder.

I don’t think currently apothecary is shipped with nightlys until it’s
usable.

We a few days off now fully documented and cross platform. If you would
like to test poco libs compiled with vs2022 let me know

**Comment by danzeeeman** [comment]
this poco and openssl should work now
https://drive.google.com/drive/folders/1koqR6sytOHbuW5aS-QWE9bS_xvXm-q0Q?usp=drive_link

**Comment by danoli3** [comment]
Also for anyone finding this, use Git Bash or Windows Bash and it sorts it out all
