### ISSUE TITLE
Actions Find replacement for Update-Release action 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#359]
Need to find a replacement for 
```
 uses: johnwbyrd/update-release@v1.0.0
```

```
<!DOCTYPE html>
build-macos-platforms (3)Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: johnwbyrd/update-release@v1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
--
build-macos-platforms (3)The following actions uses node12 which is deprecated and will be forced to run on node16: johnwbyrd/update-release@v1.0.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
build-macos-platforms (3)

[build-macos-platforms (3)](https://github.com/openframeworks/apothecary/actions/runs/8232163873/job/22508987861)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: johnwbyrd/update-release@v1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
[build-macos-platforms (3)](https://github.com/openframeworks/apothecary/actions/runs/8232163873/job/22508987861)
The following actions uses node12 which is deprecated and will be forced to run on node16: johnwbyrd/update-release@v1.0.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[build-macos-platforms (3)](https://github.com/openframeworks/apothecary/actions/runs/8232163873/job/22508987861#step:13:17)
```

16 about to marked as unusable due to security issues. 
OG @johnwbyrd has archived his repo, unless he wants to update it, we need to replace it with another one

**Comment by danoli3** [comment]
https://github.com/marketplace/actions/gh-release

**Comment by danoli3** [comment]
This is actually causing a bug randomly with one of the release tags conflicting, need to address this as having to manually go in and remove XROS 03 randomly for a build success on bleeding main/master

**Comment by johnwbyrd** [comment]
I do not recommend that you depend on that code.  I initiated it as an experiment at the time, and since then many superior options have surfaced.

**Comment by dimitre** [comment]
softprops/action-gh-release ?

**Comment by danoli3** [comment]
I'm not sure if action-gh-release is working on projectGenerator it seemed to have some serious issues recently

**Comment by danoli3** [comment]
Thanks @johnwbyrd it has worked great for a long time regardless haha!

There is currently an issue just manfiested today deploying gzip to release with the trailing & and failing on windows releases today

**Comment by danoli3** [comment]
Okay this is currently the main issue the VS releases... we need to look at replacing the GH Action

**Comment by dimitre** [comment]
I'm using softprops/action-gh-release@v2.0.8 
here https://github.com/dimitre/ofbuild

**Comment by danoli3** [comment]
Nice this is looking good. I've just re-written the VS actions to support this softprops release and its working great.

Also I've added support for TAGS to auto build to those tags. Looking good! 

Updating artifacts to use tags/release to fix any cache issues I could think of. 

Re: Tags: This will allow for @ofTheo to just tag at any point the libraries to a version and it will auto build to releases, ez pz

**Comment by dimitre** [comment]
Hey @danoli3 great news! I suggest we use tags for any apothecary changes, so for a specific OF release it can point to a specific Apothecary release.
I've been using tags for release versions here https://github.com/dimitre/ofbuild/releases

**Comment by dimitre** [comment]
about versions: if apothecary is broken again for any reason we can hang on a specific version

**Comment by danoli3** [comment]
Yeah tags are now working it will build for that tag, I'm testing with Latest, but any tag will work, version number etc. Just fixing up some cache issues

**Comment by danoli3** [comment]
We can apply the same code to pG and oF releases also

**Comment by dimitre** [comment]
Yes. it will be great! we can have lots of intermediate releases in OF it will be great
and PG is great. nice to debug with ever incrementing versions

**Comment by danoli3** [comment]
Working good!
