### ISSUE TITLE
Support for building multiple OS X ARCH + lipo?

### ISSUE THREAD

**Issue by pizthewiz** [openframeworks/apothecary#36]
The [README](https://github.com/openframeworks/apothecary/tree/master/scripts/apothecary#creating-fat-libs-for-osx--ios) mentions two strategies to build fat, the first is a manual approach (build, rename folder, build other arch and  `lipo`) and the second:
> 2 build as arch1, arch2, ... simultaneously -> the linking system automatically creates a fat lib
>
> Both methods work, but one may be easier than the other based on the library's build system. For method one, you probably need to copy the built lib file after each build step and rename it based on the architecture or it may be overwritten by the next build.
> 
> *Note: `lipo -info` can tell you the architectures currently in a compiled lib: `lipo -info libsomelib.a`*

Does this mean the `apothecary` tool itself can be run with multiple architectures and it will `lipo` on our behalf? I tried
```sh
$ ./apothecary -a 32 -a 64 -t osx OpenCV
```
And it seemed as though the second architecture overrode the first. The reason I'm asking about this specific behavior is because the OS X 64-bit/C++11 plan for OF 0.9.0 is shaping up to use `libstdc++` for 32 and `libc++` for 64. We could use the first strategy but if there were direct tooling support that would definitely help avoid errors that could otherwise be introduced through the manual process.

CC @admsyn

**Comment by danoli3** [comment]
This kind of became just was merged when we went full libc++
