### ISSUE TITLE
VS latest libs - only selected platform

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#377]
it would be great to install only the libs for selected platform
we are having lots of issues with bleeding libs, and it takes a while to install all platforms

**Comment by danoli3** [comment]
Prior libraries - Total (x64) - 143.5 MB
Bleeding Libraries - **Total (arm64, x64, arm64ec) - 167.23 MB**
Bleeding Libraries - **Total (x64 only) - 55 MB**


in openFrameworks main download_libs supports this via passing BITS
```
if [ ! -z ${BITS+x} ]; then
    ../dev/download_libs.sh -p vs -b -a $BITS -n $@
else
    ../dev/download_libs.sh -p vs -b -a 64 -n $@
    ../dev/download_libs.sh -p vs -b -a arm64 -n $@
    ../dev/download_libs.sh -p vs -b -a arm64ec -n $@
fi          
```
 
 So could just make another script if you want where can just run from script dir 
 download_latest_x64.sh
```
 #!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR
if [ ! -z ${BITS+x} ]; then
    ../dev/download_libs.sh -p vs -b -a $BITS -n $@
else
    ../dev/download_libs.sh -p vs -b -a 64 -n $@
fi 
```

**Comment by danoli3** [comment]
Okay that's merged

**Comment by danoli3** [comment]
Also cleaning up macOS stuff, was packaging all variants
