### ISSUE TITLE
curl certificate error on windows

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#378]
I'm trying to install libs (latest or regular) on a windows machine, remotely and there are some curl errors there. I've checked the clock and it is ok. Anything else to try?
Thanks

```
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - A fun▒▒o de revoga▒▒o n▒o p▒de verificar a revoga▒▒o do certificado.
```

**Comment by danoli3** [comment]
Are you running the scripts via bash, ps or cmd?
what do you get when you type command in terminal:  curl -V 
```
 curl -V
curl 8.7.1 (x86_64-w64-mingw32) libcurl/8.7.1 Schannel zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd
```

Lets get the wget2 stuff in main as well see if that fixes

**Comment by danoli3** [comment]
I'll cherry pick your wget2 changes and add my ones, its currently wget2 working on apothecary for downloading git releasing with great success on my local

**Comment by danoli3** [comment]
Safe to say this one fixed now
