### ISSUE TITLE
64bit / libc++ formulas - check list ( all platforms )

### ISSUE THREAD

**Issue by admsyn** [openframeworks/apothecary#39]
This is an issue for tracking progress on 64bit / libc++ support for all platforms

crucial: 
- [x] poco / ( all done https://github.com/openframeworks/openFrameworks/pull/3116 ) 
- [x] FreeImage - ( https://github.com/openframeworks/openFrameworks/pull/3143 )
 - [x] osx
 - [x] ios 
 - [x] vs 
 - [x] win_cb
 - [ ] android
- [x] FreeType / ( https://github.com/openframeworks/openFrameworks/pull/3152 ) 
 - [x] osx
 - [x] ios 
 - [x] vs 
 - [ ] win_cb
 - [x] android
- [x] cairo
- [x] fmodex
- [x] glew (https://github.com/openframeworks/openFrameworks/pull/3291)
 - [x] osx
 - [x] vs 
 - [x] win_cb
 - [ ] linux and arm
- [x] glfw - ( https://github.com/openframeworks/openFrameworks/pull/3239 ) 
 - [x] osx
 - [x] vs 
 - [x] win_cb
 - [x] linux and arm
- [x] kiss
- [ ] rtAudio
- [x] tess2 / ( needs all https://github.com/openframeworks/openFrameworks/pull/3150 ) 
- [ ] assimp / (needs win/android/arm  https://github.com/openframeworks/openFrameworks/pull/3237 )
 - [x] osx
 - [x] ios 
 - [x] vs 
 - [ ] win_cb
 - [x] android
- [x] opencv / ( needs win/android/arm https://github.com/openframeworks/openFrameworks/pull/3137 )
 - [x] osx
 - [x] ios 
 - [x] vs 
 - [x] win_cb
 - [x] android
- [x] openssl / ( only built for iOS https://github.com/openframeworks/openFrameworks/pull/3171 )
 - [x] osx
 - [x] ios 
 - [x] vs 
 - [x] win_cb
 - [x] android

lower priority:
- [x] tinyxml ( compiles from source - good to go ) 
- [x] oscpack - (compiles from source - good to go.  https://github.com/openframeworks/openFrameworks/pull/3210 ) 
- [x] glut - no 64bit GLUT - 0.9.0 and on focus on GLFW 
- [x] svgTiny ( compiles from source ) 

( previous discussion: http://dev.openframeworks.cc/pipermail/of-dev-openframeworks.cc/2014-June/033583.html )

**Comment by danoli3** [comment]
All done :+1:
