### ISSUE TITLE
unable to lookup 'SDKVersion' in SDK 'iphoneos' 

### ISSUE THREAD

**Issue by hiroMTB** [openframeworks/apothecary#400]
## issue
I tried to compile OpenCV on my macOs local machine and got an error `unable to lookup 'SDKVersion' in SDK 'iphoneos' `

## temporary quick solution
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

## Related
https://github.com/nodejs/node-gyp/issues/569

**Comment by danoli3** [comment]
Nice! Yeah maybe due to Xcode 16 install?

**Comment by hiroMTB** [comment]
Thanks @danoli3!
I didn't know that there are 3 command line tools(by homebrew,  terminal and xcode) installed. 
For those who come here in future, 
- https://mac.install.guide/commandlinetools/#:~:text=Xcode%20Command%20Line%20Tools%20are,environment%20for%20programmers%20named%20Xcode.
- https://apple.stackexchange.com/questions/378316/how-to-delete-command-line-tools-while-keeping-xcode
