### ISSUE TITLE
Add any new apothecary issues to openFrameworks

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/apothecary#42]
This repo is only used for tracking issues and will be removed when the issues here are closed or migrated.

**Comment by bilderbuchi** [comment]
@bakercp @admsyn @pizthewiz @openframeworks/core could you go through the issue tracker and check and close issues where proper, so we can close/shut down this repo?

**Comment by danoli3** [comment]
I think it's ready to be shut down now to be honest. All the issues are so old.

**Comment by bilderbuchi** [comment]
thanks! I'll shut down the issue tracker, then.
