### ISSUE TITLE
VS/PG Project Links to `libs/freeImage` (Folder is called `libs/FreeImage`)

### ISSUE THREAD

**Issue by GitBruno** [openframeworks/apothecary#434]
Not sure where to fix.

    $(OF_ROOT)\libs\freeImage\include

**Comment by danoli3** [comment]
Shouldn't cause too much issue with caseType, but maybe on certain hard drive formats it could! 

Added fix #8112

**Comment by danoli3** [comment]
Merged thanks @GitBruno
