### ISSUE TITLE
Remove Fmod

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#439]

**Comment by roymacdonald** [comment]
Hi, I would not give for granted that FMOD is no longer being used on all platforms. On macos it is no longer used, but I think I did not remove it from the builds in iOS and other apple environments. 
On windows, I think there is a caveat related to whether ofMediaFoundationSoundPlayer is supported or not.

**Comment by danoli3** [comment]
iOS is all good doesn't use it. Re-added for VS totally!

**Comment by roymacdonald** [comment]
Correct, iOS is not using it but the projects still expect it to be there and will fail if not found. I did a PR removing the need for it from macos but not from ios.
