### ISSUE TITLE
Poco update to 1.6.1

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#44]
Release has been out for a while now:
https://github.com/pocoproject/poco/releases/tag/poco-1.6.1-release

Adds support needed for tvOS as well. 

Update formula ?

**Comment by danoli3** [comment]
I.E.

https://github.com/openframeworks/openFrameworks/pull/4808

@bakercp could you PR the script changes here?

**Comment by arturoc** [comment]
Update formula ?

Yes please, just send a PR and lets see if it builds ok in all platforms

**Comment by danoli3** [comment]
Actually, is it possible to hit this SHA just past the 1.6.1 release:
SHA=f8dee428ab61499753e9b2f81f8a5b9ea1dc74e4

This fixed critical code to support tvOS.

**Comment by danoli3** [comment]
Looks like 1.7.0 is meant to be out last week, so maybe in the next week 1.7.0 will be out regardless.

**Comment by danoli3** [comment]
I can just grab @bakercp 's changes directly if he doesn't mind.
