### ISSUE TITLE
Formula with ~

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#45]
Just noticed a few of these around the place on this repo:

https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/poco/poco.sh%7E

poco.sh~ 

Are these left over things?
Can we remove them?

**Comment by arturoc** [comment]
yeah that shouldn't be there i must have commited them by accident, feel free to remove them directly in master

**Comment by danoli3** [comment]
Fixed
