### ISSUE TITLE
some windows arm64ec libraries failing

### ISSUE THREAD

**Issue by dimitre** [openframeworks/apothecary#453]
I think we should disable them for now and develop and get it right in a separate branch. 
incorporate only when everything is done right.

I've read something that can help is installing this, version 22000:
https://github.com/marketplace/actions/setup-windows-10-sdk-action

**Comment by danoli3** [comment]
It was caused by Microsoft's Visual Studio SDK update breaking some things in the toolchains across the board.

Looking into it

**Comment by danoli3** [comment]
```
WIN10_INSTALLED_SDK_2019=10.0.190410.0
WIN10_INSTALLED_SDK_2019_HEX=0x0A004A31

WIN10_INSTALLED_SDK_2022=10.0.20348.0
WIN10_INSTALLED_SDK_2022_HEX=0x0A004F5C

WIN11_INSTALLED_SDK_2022=10.0.22621.0
WIN11_INSTALLED_SDK_2022_HEX=0x0A00586D

```

needs to be updated as it auto switched to latest 
![image](https://github.com/user-attachments/assets/cc9f8342-a6ec-4413-93bc-6b31580ed895)

**Comment by danoli3** [comment]
even more issues with cmakelists found.
```
  # kill security checks which are dependent on stdlib
  #target_compile_options (glew PRIVATE -GS-)
  #target_compile_options (glew_s PRIVATE -GS-)
  # remove stdlib dependency
  #target_link_libraries (glew LINK_PRIVATE -nodefaultlib -noentry)
  #target_link_libraries (glew LINK_PRIVATE libvcruntime.lib)
  #target_link_libraries (glew LINK_PRIVATE msvcrt.lib )
  #string(REGEX REPLACE "/RTC(su|[1su])" "" CMAKE_C_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG})
  ```
  Removed these as we specify the type dynamically. Old Cmakelist code from 9 years ago. Packaged fix now 
  
  ```glew.sh``` to ```glew/glew.sh```
  + ```glew/CMakeList.txt```
