### ISSUE TITLE
Platform osx broken if ios SDK not installed

### ISSUE THREAD

**Issue by Daandelange** [openframeworks/apothecary#460]
Hi,

Using latest master, the osx update script fails because the ios SDK is not installed while I'm providing args: `-t osx`.
My environment: `osx 10.15`, `of_0.12.0_release` (with apothecary cloned), `XCode 12.4`. No iOs SDK nor tvOs SDK.
_Note: Also failing with an apothecary version from `of_0.11.0` era (in of_v0.11.0_release). _

1. [These 2 lines](https://github.com/openframeworks/apothecary/blob/313b213ede658eb6ae3fa5c4fb21a7bdcbe2230a/apothecary/apothecary#L99-L100) print : `xcrun: error: SDK "iphoneos" cannot be located`.
2. [This line](https://github.com/openframeworks/apothecary/blob/313b213ede658eb6ae3fa5c4fb21a7bdcbe2230a/apothecary/apothecary#L2455) throws `xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphoneos' ^  ^ Received errexit on line 2456 ./apothecary/apothecary` and kills the script.

Workaround : Commenting out line 2455 lets apothecary run normally.

**Comment by dimitre** [comment]
@danoli3 I think this one is related to the fact that "macos" platform is missing a package.
which action build which platform? 

I'm wondering if macos action is building osx platform
and xcframework action is building macos platform.

if this is the case it is super confusing

**Comment by Daandelange** [comment]
I was running `./apothecary/apothecary -t osx  -a x86_64 update ofxDlib` (to update ofxDlib).  
(I had the same issue using `./apothecary/apothecary update glfw` so it's not ofxDlib related).

````
% xcrun --version
xcrun version 59.

% xcrun -sdk macosx --show-sdk-version
11.1

% xcrun -sdk iphoneos --show-sdk-version
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphoneos'
````

Here's a more reliable fix + warning to fix [at line 99](https://github.com/openframeworks/apothecary/blob/313b213ede658eb6ae3fa5c4fb21a7bdcbe2230a/apothecary/apothecary#L99-L100). (doesn't need the above workaround)
````sh
    # Below is original line 99 (note the change in encapsulation so $? works)
    IOS_LATEST_SDK=`xcrun -sdk iphoneos --show-sdk-version` # stupid hack to keep my syntax highlighting from breaking :P
    # if command failed set fallback value: ex iOS SDK not installed
    if [ $? -eq 1 ]; then
        echo "Failed determining iOS SDK ! Setting to empty."
        IOS_LATEST_SDK="" # Note: Setting this to "unknown" will throw later: `unknown: command not found`.
    fi
````

**Comment by danoli3** [comment]
Yeah if SDK not installed for iOS or tvOS it would not function! 

Fixed now and also proper warning / error if building for iOS or tvOS and not installed:
https://github.com/openframeworks/apothecary/commit/b5f441d123af3f5379e8f5259d8ec9987d0f576f
