### ISSUE TITLE
Remove old libs from ci.openframeworks.cc/libs

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#50]
@arturoc you might need to do this will shell/sftp.

http://ci.openframeworks.cc/libs/

Remove:
- http://ci.openframeworks.cc/libs/openFrameworksLibs_master_android.tar.bz2
- http://ci.openframeworks.cc/libs/openFrameworksLibs_master_ios.tar.bz2
- http://ci.openframeworks.cc/libs/openFrameworksLibs_master_linux.tar.bz2
- http://ci.openframeworks.cc/libs/openFrameworksLibs_refactor-travisbuilds_linux.tar.bz2

**Comment by arturoc** [comment]
done, thanks!
