### ISSUE TITLE
Steps to Include Official Packaged Addons

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#53]
Options:
- Add the addon formulas in with the normal formula's folder - Let the downloader script deal with managing on the other end (so package normally).
- Seperate Formula Folder for Addons, then built to special folder to be dealt with by downloader scripts.
- ??

**Comment by arturoc** [comment]
yes i think we should just move the addons formula into the normal folder and then let the script move them to their correct places when downloading. it would be the simplest and we only have 2 or even none in some platforms.

**Comment by danoli3** [comment]
Alrighty while I wait for Xcode to update... I'll set this up

**Comment by danoli3** [comment]
Alrighty: https://github.com/openframeworks/apothecary/pull/55
Some issues in linux about zip for assimp.
