### ISSUE TITLE
Always have compilation error ^ Received error ^

### ISSUE THREAD

**Issue by baydam** [openframeworks/apothecary#63]

**Comment by tgfrerer** [comment]
hey @baydam, could you tell a bit more?
* what operating system are you using, which version?
* what command caused the error?
* what else does the error message say?
* what were you trying to do when the error happened?

**Comment by baydam** [comment]
Hello, 
Am using Debian Testing and I have this error when I execute install_depencies script which comes with Openframeworks package. During the installation when ask me to compile Poco I got this follows error message: 
ranlib /opt/openFrameworks/scripts/apothecary/build/poco/lib/Linux/x86_64/libPocoNet.a
make[1]: Leaving directory '/opt/openFrameworks/scripts/apothecary/build/poco/Net'

^ Received error ^

**Comment by arturoc** [comment]
i think this is a problem with the poco version we use not being compatible with the latest openssl included in debian testing since recently. i don't think this will be fixed in the current stable versions (0.9.x) but the nightly builds should work without problem
