### ISSUE TITLE
realpath on mac

### ISSUE THREAD

**Issue by Daandelange** [openframeworks/apothecary#65]
Trying to use apothecary with OF 0.9.8 + OSX 10.12 the apothecary script kept throwing errors.
It seems like `realpath` is not installed by default on Sierra.
To fix, I could `brew install coreutils`.
Should there be an OSX-apothecary-install-script ?

**Comment by arturoc** [comment]
yeah that would be useful, wget is also needed

**Comment by ofTheo** [comment]
I wonder if we could avoid using realpath for OS X?
adding a requirement to have brew installed seems like an extra step that might not be needed. 

For wget OS X equivalent is: 
`curl -O <url>`

@Daandelange where in the script are you getting the error?

**Comment by Daandelange** [comment]
@ofTheo On every line where `realpath` is called in [`apothecary/apothecary`](https://github.com/openframeworks/apothecary/blob/master/apothecary/apothecary) a line error is thrown saying the execution failed, ending up in a (weird?) failure message. Also, the setting variables are not set.  
```terminal
$ ./apothecary update core
./apothecary: line 111: realpath: command not found
./apothecary: line 112: realpath: command not found
./apothecary: line 113: realpath: command not found
./apothecary: line 114: realpah: command not found
OF: 
APOTHECARY: /Developer/openFrameworks/scripts/apothecary/apothecary
FORMULAS: 
BUILD: 
LIBS_DIR: 
ADDONS: /addons
 No formula for lib "PROGRESS"
```
Alternatively I found [a series of replacement-functions to realpath](http://unix.stackexchange.com/questions/101080/realpath-command-not-found) and [some more](http://flummox-engineering.blogspot.com/2014/06/getting-absolute-path-in-bash-in-osx.html).  
There's also a more lightweight dependency : [`realpath-osx`](https://github.com/harto/realpath-osx)

**Comment by arturoc** [comment]
@ofTheo this scripts now run on the test servers so we won't need to run them locally most of the time. realpath is really useful to figure out some things and wget is usually more reliable than curl since it retries a certain number of times and in the case of linux is always there by default while you have to manually install curl so if we changed it we would need to install curl for every other platform anyway.

**Comment by arturoc** [comment]
btw, @Daandelange why are you trying to run apothecary locally? all the libraries are now automatically compiled whenever something changes and can be found here: http://ci.openframeworks.cc/libs

**Comment by ofTheo** [comment]
@arturoc - ahh that makes sense. in that case its not a huge ask, if most of the time it won't be needed to be run locally. Also didn't realize how many places the realpath was used in. 
Totally agree then! 

Maybe just add a note in the ReadMe or a setup script as @Daandelange suggests. 
Cheers!!

**Comment by Daandelange** [comment]
I know but I was (too?) curious while trying to compile OF 0.9.8 on
osx10.12 with Qt Creator 4.1.0 and it fails linking with `curl.a`; I
thought recompiling could help... but I'm on the wrong way for that issue
here. Anyways, I got the library to recompile :)
Looks promising being able to use apothecary with addons too !

**Comment by Daandelange** [comment]
Note: I just noticed there's an osx install script in `/scripts/osx/install.sh` already installing coreutils. :)
Closing this issue.

**Comment by bakercp** [comment]
I'd like to re-open this.  For situations where we have addons that require custom ofx add-on builds that use apothecary, we need to have a little easier support for people who don't have the full master branch cloned.  Possible solutions:

- Replace `realpath` and `wget`
- Include `scripts/osx/install.sh` in the distribution version of OS X 

By the way, I'm also missing realpath on linux / OS X builds when I use the addons/ci scripts, so this would solve that problem too.

**Comment by arturoc** [comment]
as @Daandelange noted when closing the issue there's already a scripts/osx/install.sh script that installs the necessary bits. isn't that enough? this tools are used cause they are much more reliable than the alternatives so i don't think substituting them is a good idea.

**Comment by bakercp** [comment]
Got it. I was looking in the openFrameworks/scripts/osx dir.
