### ISSUE TITLE
Addon formula building broken.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/apothecary#68]
Hi @arturoc 

At some point in the last few months, addon formula building broke.

There are currently a handful of variables that are now orphaned, e.g.

- `REL_LIBS_DIR`
- `REL_ADDONS_DIR`

It appears that these were removed here:

https://github.com/openframeworks/apothecary/commit/fc7d1667c795b6eb8aaf84680ec64fe594db6e1d

**Comment by bakercp** [comment]
So we end up with things like this ...

```bash
MY_TERMINAL$ ./apothecary -v -j8 update ofxDlib
OF: /Volumes/openFrameworks
APOTHECARY: /Volumes/openFrameworks/scripts/apothecary/apothecary
FORMULAS: /Volumes/openFrameworks/scripts/apothecary/apothecary/formulas
BUILD: /Volumes/openFrameworks/scripts/apothecary/apothecary/build
LIBS_DIR: /Volumes/openFrameworks/scripts/apothecary
ADDONS: /Volumes/openFrameworks/addons
Valid build types: osx linux linux64 linuxarmv6l linuxarmv7l vs msys2 ios tvos android emscripten
Build type: osx
Architecture: 32
Build dir: /Volumes/openFrameworks/scripts/apothecary/apothecary/build
Libs dest dir: /Volumes/openFrameworks/scripts/apothecary
Running: update ofxDlib
./apothecary: line 463: REL_ADDONS_DIR: unbound variable
```

**Comment by arturoc** [comment]
huh weird i don't remember why i removed this, since the addons formulas are now built in the core i might have missed that this was needed to build addons there. if you want to bring them back?

**Comment by danoli3** [comment]
This is working! Tested
