### ISSUE TITLE
How to associate addons with their libs?

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/apothecary#76]
We used to have the formulas for addons in the core addons themselves. But now I see ofxOpenCV doesn't have the formulas. 

Just wondering how I should let the project generator or the CI know that the ofxKinect addons needs libusb for VS and OS X

Thanks!
Theo

**Comment by arturoc** [comment]
when the CI servers compile the libraries in master in this repo they upload the resulting libraries here:

http://ci.openframeworks.cc/libs

then the `download_scripts.{sh,ps1}` scripts downloads them and puts the addons ones back where they should be. the script is yet not copying the kinect libraries to the correct place but it should be just a matter of adding a new rule for those. similar to:

https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/download_libs.sh#L188-L189

the first array has an entry with the name of the libraries and the second one the name of the corresponding addon (there should be the same number of entries in both arrays so if an addon has 2 libraries it's name will be repeated in the second array)

The windows script does something similar: https://github.com/openframeworks/openFrameworks/blob/master/scripts/vs/download_libs.ps1#L76-L83  but in that case there's only one array with the full path of the libraries

The script that creates the nightly builds and release packages uses the download_libs script so whenever that one is working the nightly builds will have the kinect libraries in the right place

**Comment by ofTheo** [comment]
@arturoc awesome - thank you! I knew there was a step I was missing :)
