### ISSUE TITLE
REL_LIBS_DIR throwing error when trying to build 

### ISSUE THREAD

**Issue by danzeeeman** [openframeworks/apothecary#81]
https://github.com/openframeworks/apothecary/blob/6731f7c4d576ca85515bccc19a4c73ebcfd59589/apothecary/apothecary#L1123

line 1123 throws unbound variable

**Comment by danzeeeman** [comment]
also realpath is undefined on macOS now and fails
a quick fix 

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

**Comment by danoli3** [comment]
Yeah realpath gone in High Sierra (10.13).
I'll make a wrapper

**Comment by bakercp** [comment]
Just following up on this -- and this still applies to the Androind R15 branch).

Currently the libs directory for addons is not being set correctly by default (it can be set correctly with `-d`).

Basically with the recent changes:

```
# use default libs dir?
if [ "$LIBS_DIR" == "" ] ; then
	LIBS_DIR=$APOTHECARY_DIR/$REL_LIBS_DIR
else # manually set
	case $LIBS_DIR in
		/*) : ;; # absolute path
	 	*) LIBS_DIR=$WD/$LIBS_DIR ;; # relative path
	esac
	IS_CUSTOM_LIBS_DIR=1
fi
```

`IS_CUSTOM_LIBS_DIR` is always getting set to 1, and therefore it can't pick up the correct path automatically.

Anyway, @danoli3  and @danzeeeman is this an issue you all are working on or would you like some help getting the LIBS_DIR and LIBS_REL_DIR working right?  Let me know.

**Comment by danoli3** [comment]
I have debugged this and found the problem now fixed in https://github.com/openframeworks/apothecary/pull/231
