### ISSUE TITLE
Apothecary not working on Raspbian Stretch

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/apothecary#99]
OF isn't compiling on Pi 3 B+ because of Poco issues. If I try to use apothecary to update, I get the below error. I also had the same issue on an Odroid XU4 running Ubuntu Mate.

./apothecary -tlinuxarmv6l update poco
OF: /home/pi/openFrameworks/scripts/apothecary/apothecary/../../../
APOTHECARY: /home/pi/openFrameworks/scripts/apothecary/apothecary
FORMULAS: /home/pi/openFrameworks/scripts/apothecary/apothecary/formulas
BUILD: /home/pi/openFrameworks/scripts/apothecary/apothecary/build
LIBS_DIR: /home/pi/openFrameworks/scripts/apothecary/apothecary/../
ADDONS: /home/pi/openFrameworks/scripts/apothecary/apothecary/../../../addons
REL_ADDONS_DIR: /home/pi/openFrameworks/scripts/apothecary/apothecary/../../../addons
./apothecary: line 1238: TOOLCHAIN_PREFIX: unbound variable

What should TOOLCHAIN_PREFIX be set to?

Thanks!

**Comment by bakercp** [comment]
```
CROSSCOMPILING=0
if [ "$TYPE" == "linuxarmv6l" ] || [ "$TYPE" == "linuxarmv7l" ]; then
    if [ "$(uname -m)" != "armv6" -a "$(uname -m)" != "armv7" ]; then
        CROSSCOMPILING=1
        if [ -z $TOOLCHAIN_PREFIX ]; then
            export TOOLCHAIN_PREFIX=arm-linux-gnueabihf
        fi
        if [ -z $SYSROOT ]; then
            echoError Trying to cross compile but SYSROOT environment variable is not set
            echoError Should be set to root of target OS image
            exit 1
        fi
        if [ -z $TOOLCHAIN_ROOT ]; then
            echoWarning Trying to cross compile but TOOLCHAIN_ROOT not set
            echoWarning Trying to continue in case PATH is set to correct toolchain
            echoWarning If compiling fails try setting TOOLCHAIN_ROOT to root of cross compiler toolchain
        fi
    fi
fi
```

Currently apothecary assumes you will not be compiling natively on the raspberry pi, but will be cross compiling.

**Comment by bakercp** [comment]
If we change 

```
    if [ "$(uname -m)" != "armv6" -a "$(uname -m)" != "armv7" ]; then
```

```
 if [[ $(uname -m) != armv* ]]; then
```

it fixes this issue.  Modern Raspberry Pis (e.g. Rpi3) say  `$(uname -m) == armv7l`
